# -*- coding: utf-8 -*-
"""Encoding and Decoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OpoVAvnwx7ZTV5tCMDcIErTsRaCeahy1
"""

def encode_text(text):
    alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    encoding = {letter: str(index + 1) for index, letter in enumerate(alphabet)}
    return ' '.join([encoding[char.upper()] for char in text if char.upper() in alphabet])

text = "PUREDEMOCRACY"     #ENTER YOUR TEXT IN CAPITAL LETTERS ONLY!!!
a = print(encode_text(text)) # Output: "3 1 20"

def decode_text(encoded_text):
    encoded_text = [int(num) for num in encoded_text.split()]
    alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    decoding = {index + 1: letter for index, letter in enumerate(alphabet)}
    return ''.join([decoding[num] for num in encoded_text if num in decoding])

#encodd_text == a
#print(decode_text(encodd_text)) # Output: "CAT"

encoded_text = encode_text(text)
decoded_book = decode_text(encoded_text)
print(f"Original text: {text}")

assert text == decoded_book

import string

def encode_text(text):
    alphabet = string.ascii_uppercase + string.ascii_lowercase + string.digits + string.punctuation + ' '
    encoding = {char: str(index + 1) for index, char in enumerate(alphabet)}
    encoded_text = ' '.join([encoding[char] for char in text if char in encoding])
    print(f"Encoded text: {encoded_text}")
    return encoded_text

def decode_text(encoded_text):
    encoded_text = [int(num) for num in encoded_text.split()]
    alphabet = string.ascii_uppercase + string.ascii_lowercase + string.digits + string.punctuation + ' '
    decoding = {index + 1: char for index, char in enumerate(alphabet)}
    decoded_text = ''.join([decoding[num] for num in encoded_text if num in decoding])
    print(f"Decoded text: {decoded_text}")
    return decoded_text

with open('book.txt', 'r') as f:
    book = f.read()

print(f"Original text: {book}")
encoded_book = encode_text(book)
decoded_book = decode_text(encoded_book)

assert book == decoded_book

